{"ViolationName":"Avoid using 'System.err' and 'System.out' within a try catch block","ViolationId":4696,"Violations":[{"violator":2460,"bookmarks":[{"ID":1004,"file":"./test/pivotal-bank-demo-master/pivotal-bank-demo-master/e2e-tests/.mvn/wrapper/MavenWrapperDownloader.java","lineStart":68,"colStart":35,"lineEnd":68,"colEnd":35},{"ID":1005,"file":"./test/pivotal-bank-demo-master/pivotal-bank-demo-master/e2e-tests/.mvn/wrapper/MavenWrapperDownloader.java","lineStart":91,"colStart":31,"lineEnd":91,"colEnd":31},{"ID":1006,"file":"./test/pivotal-bank-demo-master/pivotal-bank-demo-master/e2e-tests/.mvn/wrapper/MavenWrapperDownloader.java","lineStart":94,"colStart":31,"lineEnd":94,"colEnd":31}]}]}